<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px" />

# Numpy Ladder Challenge 

# Climb the Ladder!
Our class moves quickly! Sometimes, it feels like we make leaps in logic that are a bit too big. In this ladder challenge, we'll learn some core math concepts and the `numpy` library. Problems in this notebook start out easy and progressively get harder, so that the next rung of the Python ladder is always within reach.

Additionally, since not all of the topics discussed in this ladder challenge are explicitly taught in our course, these problems come with many more hints, tips, suggestions, and even sometimes a mini-lesson. You are encouraged to Google frequently throughout the lesson. In many ways, this ladder is meant to be a challenge as well as educational in its own right.

# One Rule: NO LOOPS
`numpy` takes advantage of **vectorized calculations**. A vectorized calculation is where one calculation occurs throughout the entire vector. For example, for a vector `v`, if we want a vector `w` that is all the elements of `v` plus one:

```
# GOOD! This is vectorized!
w = v + 1

# BAD! This is hard to read and extremely inefficient!
for i in range(len(v)):
    w[i] = v[i] + 1
```

**None of the exercises in this notebook require a loop. If you use a loop to solve any of these problems, you are solving the problem incorrectly.**

# Section I - Vectors and some vector math

0) Import the `numpy` library, aliasing it to be `np`

In [1]:
import numpy as np

1) Make the following vector defined as `v`:
    $$\mathbf{v} = (3, -1, 5, 2, -7)$$

In [10]:
v = np.array([3, -1, 5, 2, -7])
print(v)

[ 3 -1  5  2 -7]


2) Make the following vector defined as `w` using `np.arange()`:
    $$\mathbf{w} = (2, 3, 4, 5, 6)$$

In [7]:
w=np.arange(2,7)
# print(w)

[2 3 4 5 6]


3) Find $\mathbf{v} + \mathbf{w}$.

In [12]:
sumvw=v+w
print(sumvw)

[ 5  2  9  7 -1]


4) What's the element-wise product of $\mathbf{v}$ and $\mathbf{w}$?

In [14]:
productvw=v*w
print(productvw)

[  6  -3  20  10 -42]


5) Triple every element of `v`. (Do not reassign.)

In [15]:
print(3*v)

[  9  -3  15   6 -21]


6) Double every element of `w` and then subtract 2 from every element. (Do not reassign.)

In [18]:
# print(w)
print(w*2-2)

[ 2  4  6  8 10]


7) Index `v` to show me the number `-1`.

In [25]:
print(v[ v == -1])

[-1]


8) Index `v` to show me everything except the 0th element.

In [26]:
print(v[ v != -1])

[ 3  5  2 -7]


9) Index `v` to show me the elements at index 4, 2, and 3 (in that order).

In [32]:
print(v[4], v[2], v[3])


-7 5 2


10) Reassign the element of `v` at index 2 to be 6.

In [33]:
print(v)
v[2]=6
print (v)

[ 3 -1  5  2 -7]
[ 3 -1  6  2 -7]


### Mini-Lesson: Filtering
Inequalities are also vectorized in `numpy`. For example:

```
v > 2
==> array([ True, False,  True, False, False])
```

You can also **filter** a vector using booleans, like follows:

```
v[[True, False,  True, False, False]]
==> array([3, 6])
```

The vector keeps anything `True`, and drops anything `False`.  It then follows you can filter a vector using the vector itself, like this:

```
v[v > 2]
==> array([3, 6])
```

11) Show me all of the positive elements of `v`.

In [36]:
print(v[v>0])
# print(v)

[3 6 2]
[ 3 -1  6  2 -7]


12) How many elements of `v` are positive? (Use `numpy` to answer this question, do not count manually).

In [37]:
print(np.sum(v>0))

3


13) Show me all of the even elements of `w`.

In [39]:
print( w[w % 2 == 0])

[2 4 6]


14) Show me all of the positive even elements of `v`.

In [41]:
print(v[(v%2==0) & (v>0)])

[6 2]


15) Redefine all the negative elements of `v` to be zero. This is a common sort of operation to do for real-world data! 

_Hint:_ Using `np.where` is one of two easy ways to do this. The other is the reassign the vector while filtering.  Do both ways if you can! 

In [43]:
v = np.where(v<0, 0, v)
print(v)

[3 0 6 2 0]


16) Create a new vector that's `"EVEN"` if the corresponding element of `w` is even, and `"ODD"` otherwise.

In [70]:
# print(w)
w_even=w[np.where(w%2==0)]
w_odd=w[np.where(w%2!=0)]
print(w_even)
print(w_odd)

[2 4 6]
[3 5]


# Section II - Statistics and vector operations

### Emails
For the next few problems, consider the following vector which represents the number of emails my inbox gets over the span of 20 days.

In [60]:
emails = np.array([25, 2, 45, 6, -2, 4, 4, 10, 6, -3, 16, 39, 19, 0, 1, -11, 25, 2, 7, 17])

17) A few data points were accidentally recorded as negative when they should be positive. Reassign `emails` to fix these records.

In [61]:
emails=np.where(emails<0, abs(emails), emails)
print(emails)

[25  2 45  6  2  4  4 10  6  3 16 39 19  0  1 11 25  2  7 17]


18) What is the mean number of emails I get per day?

In [62]:
print(np.mean(emails))

12.2


19) Among days where I get more than 15 emails, what is the mean number of emails I get?

In [67]:
print(np.mean(emails[emails>15]))


26.571428571428573


20) What proportion of days do I receive more than 20 emails?

In [69]:
print(np.mean(emails>20))


0.2
